apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-event-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-event-controller
  template:
    metadata:
      name: pod-event-controller
      labels:
        app: pod-event-controller
    spec:
      serviceAccountName: pod-event-controller
      containers:
        - name: main
          image: gaoxinge/pod-event-controller
        - name: proxy
          image: luksa/kubectl-proxy:1.6.2